#!groovy

pipeline {

    agent {
        node { label 'maven' }
    }

	stages {
	
		stage('Build') {
			steps {
                echo 'Building..'
                sh 'mvn clean package'
            }
		}
		
		stage ('Running') {
		
			steps {
		    	echo 'Iniciando o Spring Boot...'
                sh 'mvn spring-boot:run'
            }
            
		}
				
		
	}
}
