#!groovy

pipeline {

    agent any

	stages {
	
		stage('Build') {
			steps {
                echo 'Construindo...'
                bat 'mvn clean package'
            }
		}
		
		stage('Docker image') {
			steps {
                echo 'Gerando a Docker Image...'
                bat 'docker image build --force-rm --tag local:demo .'
            }
		}				
		
		stage ('Deploy Container') {		
			steps {
                echo 'Inicia container demo...'
                bat 'docker container run -d --name demo -p 18080:18080 local:demo'
            }            
		}
				
		stage('Performance') {
			steps {
                echo 'Checa performance projeto demo...'
                bat 'mvn clean verify -Pperformance'
            }
		}
		
		stage ('Stop Container') {		
			steps {
                echo 'Parando o container demo...'
                bat 'docker container stop demo'
            }            
		}
		
	}
}
