#!groovy

pipeline {

    agent any

	stages {
	
		stage('Build') {
			steps {
                echo 'Building..'
                bat 'mvn clean package'
            }
		}
		
		stage ('Running') {
		
			steps {
		    	echo 'Iniciando o Spring Boot...'
                bat 'mvn spring-boot:run'
            }
            
		}
				
		
	}
}
